import{a as f,i as l,S as y}from"./assets/vendor-17bd9699.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const h="45273234-8772896c6b05d52973b361fbb",g="https://pixabay.com/api/";async function p(t=1,o=15,s){var n;try{return(await f.get(g,{params:{key:h,image_type:"photo",orientation:"horizontal",safesearch:!0,q:s,page:t,per_page:o}})).data}catch(e){throw new Error(((n=e.response)==null?void 0:n.status)||e.message)}}const b="/vanilla-app-template/assets/error-06de2d57.svg";l.settings({class:"custom-toast",position:"topRight",maxWidth:432,color:"#FFFFFF",titleColor:"#FFFFFF",messageColor:"#FFFFFF",iconColor:"#FFFFFF",displayMode:1});function F(t){const o=document.getElementById("gallery"),s=t.map(e=>`
				<a href="${e.largeImageURL}" class="gallery-item">
					<div class="media">
						<img src="${e.webformatURL}" alt="${e.tags}">
					</div>
					<div class="info">
						<p class="info-item"><b>Likes</b><br/> ${e.likes}</p>
						<p class="info-item"><b>Views</b><br/> ${e.views}</p>
						<p class="info-item"><b>Comments</b><br/> ${e.comments}</p>
						<p class="info-item"><b>Downloads</b><br/> ${e.downloads}</p>
					</div>
				</a>
			`).join("");o.insertAdjacentHTML("beforeend",s),new y(".gallery a").refresh()}function L(){const t=document.getElementById("gallery");t.innerHTML=""}function E(){document.getElementById("loader").classList.remove("hidden")}function w(){document.getElementById("loader").classList.add("hidden")}function v(){document.getElementById("load-more").classList.remove("hidden")}function I(){document.getElementById("load-more").classList.add("hidden")}function B(t){l.info({message:t,backgroundColor:"#6C8CFF",iconColor:"white"})}function c(t){l.error({message:t,backgroundColor:"#EF4040",iconUrl:b})}function C(){const t=document.querySelector(".gallery-item");if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}const d=15;let i=1,u="";async function m(){I(),E();try{const t=await p(i,d,u);t.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):(F(t.hits),i++,i<=Math.ceil(t.totalHits/d)?v():B("We're sorry, but you've reached the end of search results."))}catch{c("Failed to fetch images")}finally{w()}}document.getElementById("search-form").addEventListener("submit",async t=>{t.preventDefault(),L();const o=document.getElementById("search-input").value.trim();if(u=o,i=1,!o){c("Search query cannot be empty");return}await m()});document.getElementById("load-more").addEventListener("click",async()=>{await m(),C()});
//# sourceMappingURL=commonHelpers.js.map
